apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-service
  labels:
    app: support-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-service
  template:
    metadata:
      labels:
        app: support-service
    spec:
      containers:
        - name: support-service
          image: ghcr.io/khalilmassoudi/support-service:latest
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/support_db"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8888"
            - name: EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE
              value: "http://discovery-service:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: support-service
spec:
  selector:
    app: support-service
  ports:
    - port: 8085
      targetPort: 8085
